import { Download } from "lucide-react";
import { useEffect, useState } from "react";
import Notice from "../components/Notice";
import { api, apiError } from "../services/api";

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [error, setError] = useState("");

  useEffect(() => {
    api.get("/admin/reports").then((response) => setReports(response.data)).catch((err) => setError(apiError(err)));
  }, []);

  async function downloadReport(reportId) {
    setError("");
    try {
      const response = await api.get(`/reports/${reportId}/download`, { responseType: "blob" });
      const url = window.URL.createObjectURL(new Blob([response.data], { type: "application/pdf" }));
      const link = document.createElement("a");
      link.href = url;
      link.download = `phishguard-incident-report-${reportId}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err) {
      setError(apiError(err));
    }
  }

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-2xl font-semibold text-white">Generated Reports</h1>
        <p className="mt-1 text-sm text-slate-400">PDF incident reports created by analysts and admins.</p>
      </header>
      {error ? <Notice tone="error">{error}</Notice> : null}
      <section className="overflow-hidden rounded-lg border border-line bg-panel shadow-glow">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[680px] text-left text-sm">
            <thead className="bg-panelSoft text-xs uppercase tracking-wide text-slate-400">
              <tr>
                <th className="px-4 py-3">Report ID</th>
                <th className="px-4 py-3">Incident</th>
                <th className="px-4 py-3">Generated by</th>
                <th className="px-4 py-3">Created</th>
                <th className="px-4 py-3">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {reports.map((report) => (
                <tr key={report.id} className="hover:bg-panelSoft/60">
                  <td className="px-4 py-3 font-mono text-slate-400">#{report.id}</td>
                  <td className="px-4 py-3 text-white">Incident #{report.incident_id}</td>
                  <td className="px-4 py-3 text-slate-300">User #{report.generated_by}</td>
                  <td className="px-4 py-3 text-slate-400">{new Date(report.created_at).toLocaleString()}</td>
                  <td className="px-4 py-3">
                    <button className="btn-secondary" type="button" onClick={() => downloadReport(report.id)}>
                      <Download size={16} />
                      PDF
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
